name = "bertho-ai-test"
main = "src/index.js"
compatibility_date = "2026-08-25"

[vars]
ENVIRONMENT = "test"

[[services]]
binding = "BERTHO_AI"
service = "bertho-ai"

[[services]]
binding = "BERTHO_IMAGE_AI"
service = "bertho-ai-image"

[[services]]
binding = "BERTHO_CODE_AI"
service = "bertho-ai-code"